# Generated by Django 6.1.1 on 2026-09-17 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voteledger',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='voting.candidate'),
        ),
        migrations.AddField(
            model_name='voteledger',
            name='voter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='voteledger',
            unique_together={('election', 'voter')},
        ),
    ]
