# Generated by Django 6.1.1 on 2026-09-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_voterprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterprofile',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
